version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    network_mode: host
    volumes:
      - ./cardano-configurations/network/testnet:/config
      - ./db:/db
      - ./ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/config/cardano-node/config.json"
      , "--topology", "/config/cardano-node/topology.json"
      , "--database-path", "/db"
      ]

  hydra-node:
    image: ghcr.io/input-output-hk/hydra-node:latest
    restart: always
    volumes:
      - ./credentials:/credentials:ro
      - ./ipc:/ipc
      - ../hydra-poc/hydra-cluster/config/:/config:ro
    ports:
      - "4001:4001"
      - "5001:5031"
    command:
      [ "--node-id", "314"
      , "--api-host", "0.0.0.0"
      , "--host", "0.0.0.0"
      , "--port", "5031"
      , "--monitoring-port", "6001"
      , "--hydra-signing-key", "/credentials/sebastian.hydra.sk"
      , "--cardano-signing-key", "/credentials/sebastian.cardano.sk"
      , "--ledger-genesis", "/config/genesis-shelley.json"
      , "--ledger-protocol-parameters", "/config/protocol-parameters.json"
      , "--network-id", "1097911063"
      , "--node-socket", "/ipc/node.socket"
      , "--peer", "52.47.187.1:5001"
      , "--peer", "104.199.110.95:5001"
      , "--hydra-verification-key", "/credentials/arnaud.hydra.vk"
      , "--hydra-verification-key", "/credentials/matthias.hydra.vk"
      , "--cardano-verification-key", "/credentials/arnaud.cardano.vk"
      , "--cardano-verification-key", "/credentials/matthias.cardano.vk"
      ]
